# Generated by Django 5.0.4 on 2024-05-02 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='TTC_article',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='unit_type',
            field=models.CharField(choices=[('R', 'Heur'), ('P', 'Meter')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
