# Generated by Django 5.0.4 on 2024-05-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_article_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_date_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='total',
        ),
        migrations.AlterField(
            model_name='article',
            name='tva',
            field=models.DecimalField(choices=[(0, '0%'), (0.17, '17%'), (0.19, '19%')], decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='unit_type',
            field=models.CharField(choices=[('H', 'Hour'), ('M', 'Meter')], max_length=1),
        ),
    ]
