# Generated by Django 5.0.4 on 2024-05-03 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_remove_article_article_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
