# Generated by Django 5.0.4 on 2024-05-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_alter_article_article_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_date_time',
            new_name='article_date',
        ),
    ]
