# Generated by Django 5.0.4 on 2024-05-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_remove_invoice_invoice_date_time_and_more'),
        ('invoice_app', '0010_entrepreneur'),
    ]

    operations = [
    ]
