# Generated by Django 5.0.4 on 2024-05-21 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0011_merge_20240521_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
