# Generated by Django 5.0.4 on 2024-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0012_remove_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='age',
            field=models.CharField(max_length=2),
        ),
    ]
