# Generated by Django 5.0.4 on 2024-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0016_invoice_entrepreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='company',
            field=models.CharField(default=1, max_length=132),
            preserve_default=False,
        ),
    ]
