# Generated by Django 5.0.4 on 2024-06-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0017_entrepreneur_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
