# Generated by Django 5.0.6 on 2024-06-29 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0018_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='address',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='age',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='bank',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='bankaccount',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='city',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='iban',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='phone',
            field=models.CharField(default=1, max_length=132),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Feminine')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='swift',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firma',
            name='zip_code',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
