# Generated by Django 5.0.6 on 2024-06-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0019_firma_address_firma_age_firma_bank_firma_bankaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='logo',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
