# Generated by Django 5.0.4 on 2024-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0020_alter_firma_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='username',
            field=models.CharField(default=1, max_length=132),
            preserve_default=False,
        ),
    ]
