# Generated by Django 5.0.6 on 2024-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0024_remove_invoice_entrepreneur_alter_invoice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='comments',
            new_name='comment1',
        ),
        migrations.AddField(
            model_name='invoice',
            name='comment2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
