# Generated by Django 5.0.6 on 2024-07-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0025_rename_comments_invoice_comment1_invoice_comment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrepreneur',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
    ]
