# Generated by Django 5.0.6 on 2024-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0026_delete_entrepreneur_delete_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(default=1),
        ),
    ]
